# runs

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get update && apt-get install -y jq
      - name: Checks for valid JSON in rules directory
        run: |
          for file in $(ls $GITHUB_WORKSPACE/checks/rules/); 
            do 
              jq < $GITHUB_WORKSPACE/checks/rules/$file; 
              retVal=$?
              if [ $retVal -ne 0 ]; then
                  exit $retVal
              fi
          done
